variables:
  GIT_SUBMODULE_STRATEGY: normal

platformio:
  before_script:
    - apt-get update -qq && apt-get install -y -qq pipx
    - pipx install platformio
    - export PATH="$PATH:~/.local/bin"
    - platformio lib --global install ArduinoJson TaskScheduler PubSubClient ESPAsyncTCP AsyncTCP
  script:
    - platformio ci --lib="." --board=nodemcuv2 examples/mqttBridge/mqttBridge.ino
    - platformio ci --lib="." --board=nodemcuv2 examples/basic/basic.ino -O "build_flags = -Werror"
    - platformio ci --lib="." --board=nodemcuv2 examples/startHere/startHere.ino -O "build_flags = -Wall -Wextra -Wno-unused-parameter -Werror"
    - platformio ci --lib="." --board=esp32dev examples/startHere/startHere.ino -O "build_flags = -std=c++14 -Wno-incompatible-pointer-types"
    - platformio ci --lib="." --board=nodemcuv2 examples/bridge/bridge.ino -O "build_flags = -Werror"
    - platformio ci --lib="." --board=nodemcuv2 examples/logServer/logServer.ino -O "build_flags = -Werror"
    - platformio ci --lib="." --board=nodemcuv2 examples/logClient/logClient.ino -O "build_flags = -Werror"
    - platformio ci --lib="." --lib="./examples/namedMesh/" --board=esp32dev examples/namedMesh/namedMesh.ino -O ""

catch_testing:
  before_script:
    - apt-get update -qq && apt-get install -y -qq cmake
    - apt-get install libboost-system-dev -y -qq
    - cmake . -DCMAKE_CXX_FLAGS="-Wall -Werror"
    - make
  script:
    - run-parts --regex catch_ bin/

arduino:
  before_script:
    - apt-get update -qq && apt-get install -y -qq python3-serial
    # - pipx ensurepath
    # - pipx install pyserial 
  script:
    - sh test/ci/test_arduino.sh

pages:
  script:
  - apt-get update && apt-get install -y doxygen
  - doxygen doxygen/Doxyfile
  - mv doxygen/documentation/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

pages_develop:
  script:
  - apt-get update && apt-get install -y doxygen
  - doxygen doxygen/Doxyfile
  - mv doxygen/documentation/html/ html/
  artifacts:
    paths:
    - html
  only:
  - develop 
