#define CATCH_CONFIG_MAIN

#include "catch2/catch.hpp"

#include "Arduino.h"
#include "catch_utils.hpp"
#include "painlessmesh/validation.hpp"

using namespace painlessmesh;
using namespace painlessmesh::validation;

SCENARIO("Secure random number generation works") {
    GIVEN("The SecureRandom utility") {
        WHEN("Generating random numbers") {
            uint32_t random1 = SecureRandom::generate();
            uint32_t random2 = SecureRandom::generate();

            THEN("Generated numbers should be different") {
                REQUIRE(random1 != random2);
            }
        }

        WHEN("Generating random bytes") {
            uint8_t buffer1[16] = {0};
            uint8_t buffer2[16] = {0};

            SecureRandom::generate_bytes(buffer1, 16);
            SecureRandom::generate_bytes(buffer2, 16);

            THEN("Generated byte arrays should be different") {
                bool are_different = false;
                for (int i = 0; i < 16; i++) {
                    if (buffer1[i] != buffer2[i]) {
                        are_different = true;
                        break;
                    }
                }
                REQUIRE(are_different == true);
            }
        }
    }
}
